stages:
  - test
  - build
  - maintenance

image: golang:stretch

variables:
  IMAGE_BASE_PATH: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG

test:
  stage: test
  only:
    - merge_requests
    - master
  script:
    - make lint test

build:
  stage: build
  only:
    - master
  except:
    - schedules
  before_script:
    - apt-get -qq update
    - apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - apt-get -qq update
    - apt-get -y install docker-ce docker-ce-cli containerd.io
  script:
    - docker login --username "$CI_REGISTRY_USER" --password "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker pull $IMAGE_BASE_PATH:latest || true
    - docker pull $CI_REGISTRY_IMAGE/master:latest || true
    - docker build
      --pull
      --cache-from $IMAGE_BASE_PATH:latest
      --cache-from $CI_REGISTRY_IMAGE/master:latest
      -t $IMAGE_BASE_PATH:$CI_COMMIT_SHA
      -t $IMAGE_BASE_PATH:latest
      .
    - docker push $IMAGE_BASE_PATH:$CI_COMMIT_SHA
    - docker push $IMAGE_BASE_PATH:latest